### ISSUE TITLE
Landmark

### ISSUE THREAD

**Issue by wafakun** [cansik/multi-pose-landmark-mediapipe#2]
How to get keypoint landmark

**Comment by cansik** [comment]
It works the same as with the original mediapipe pose estimation. Just read the landmarks from here: https://github.com/cansik/multi-pose-landmark-mediapipe/blob/main/pose.py#L58

**Comment by wafakun** [comment]
How to display more specific coordinates eg noise coordinates

**Comment by cansik** [comment]
This is a very specific repository for a multi-pose implementation. For general issues with mediapipe, please refer to the [mediapipe pose solution](https://github.com/google/mediapipe/blob/master/docs/solutions/pose.md).

**Comment by wafakun** [comment]
Oke thanks
